### ISSUE TITLE
Question: how would you migrate an existing typo3 cms to k8s using this chart ?

### ISSUE THREAD

**Issue by softlion** [crinis/typo3-helm-chart#1]
Hi crinis,
i have a sql dump and the content of the html folder of an existing typo3 installation.

What is the best/fastest way to move it into k8s using this helm chart ?

**Comment by crinis** [comment]
To import your SQL dump you could just use something like:
`kubectl -n namespace exec -i my_sql_pod_name -- mysql -u user -ppassword < dump.sql`

To get the docroot data into the TYPO3 pod you can either mount the volume or use kubectl cp... and copy the usual directories like fileadmin, typo3conf, ... No need to add typo3_src or symlinks to it. They will be setup automatically.
